import https from "https";
import nodemailer from "nodemailer";

const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
const GMAIL_USER = process.env.GMAIL_USER;
const GMAIL_PASS = process.env.GMAIL_PASS;
const RECIPIENTS = ["robson.privado@madeiramadeira.com.br","fernando.belleza@madeiramadeira.com.br","alexandre.pereira@iguanafix.com.br","bianca.pessoa@madeiramadeira.com.br","lucas.navarro@madeiramadeira.com.br"];
const DATA = `DADOS S1-S10/2026 (R$k): GMV TOTAL S10=1098 WoW+17,6%. GMV Automatico=598 WoW+13,9%. GMV App=306 WoW+19,5%. GMV Site=277 WoW+7,3%. GMV GuideShops=306 WoW+23,6%. GMV TDV=161 WoW+25,8%. GMV Avulso=60 WoW-18%. Conversao=23,6% recorde historico. AOV=240. CONTEXTO: Marketplace servicos para casa. Canais: App/Site (digital), GuideShops (loja fisica), TDV (vendedor dedicado), Avulso (montagem, limpeza, impermeabilizacao).`;

function post(h,p,hd,b){return new Promise((res,rej)=>{const d=JSON.stringify(b);const r=https.request({hostname:h,path:p,method:"POST",headers:{...hd,"Content-Length":Buffer.byteLength(d)}},(rs)=>{let raw="";rs.on("data",c=>raw+=c);rs.on("end",()=>{try{res(JSON.parse(raw))}catch{res(raw)}})});r.on("error",rej);r.write(d);r.end()})}

function buildEmail(a){
  const today=new Date().toLocaleDateString("pt-BR",{weekday:"long",year:"numeric",month:"long",day:"numeric"});
  const sec=(num,title,color,content)=>`<div style="margin-bottom:20px;border-radius:10px;overflow:hidden;border:1px solid #e5e7eb"><div style="background:${color}22;padding:12px 18px;border-bottom:1px solid #e5e7eb"><span style="color:${color};font-weight:700;font-family:monospace;font-size:11px;margin-right:8px">${num}</span><span style="font-weight:700;font-size:13px;text-transform:uppercase;letter-spacing:0.05em">${title}</span></div><div style="padding:16px 18px;font-size:13px;line-height:1.7;color:#374151">${content}</div></div>`;
  const drivers=(a.key_drivers||[]).map(d=>`<div style="margin-bottom:12px;padding-bottom:12px;border-bottom:1px solid #f3f4f6"><strong>${d.indicador}</strong><span style="color:${d.variacao&&d.variacao.startsWith("+")?"#059669":"#dc2626"};font-family:monospace;font-size:12px;margin-left:8px">${d.variacao}</span><ul style="margin:6px 0 0 16px">${(d.drivers||[]).map(dr=>`<li style="color:#6b7280">${dr}</li>`).join("")}</ul></div>`).join("");
  const risks=(a.risks_anomalies||[]).map(r=>`<div style="margin-bottom:10px;padding:12px;background:#fff7ed;border-left:3px solid #f97316;border-radius:0 6px 6px 0"><strong style="color:#c2410c">⚠ ${r.risco}</strong><p style="margin:4px 0 0;color:#6b7280;font-size:12px">${r.driver}</p></div>`).join("");
  const actions=(a.actions||[]).map(ac=>`<div style="margin-bottom:10px;padding:12px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px"><div style="font-size:10px;color:#059669;font-family:monospace;text-transform:uppercase;margin-bottom:4px">${ac.area}</div><div>${ac.acao}</div></div>`).join("");
  const questions=(a.questions||[]).map(q=>`<li style="padding:6px 0;border-bottom:1px solid #f3f4f6;color:#374151"><span style="color:#3b82f6;font-weight:700;margin-right:6px">?</span>${q}</li>`).join("");
  const trends=(a.structural_trends||[]).map(t=>{const badge=t.tipo==="crescimento consistente"?{bg:"#d1fae5",c:"#059669",l:"▲ CRESCIMENTO"}:t.tipo==="queda consistente"?{bg:"#fee2e2",c:"#dc2626",l:"▼ QUEDA"}:{bg:"#fef3c7",c:"#d97706",l:"~ VOLATILIDADE"};return`<div style="margin-bottom:12px;padding-bottom:12px;border-bottom:1px solid #f3f4f6"><span style="background:${badge.bg};color:${badge.c};font-size:10px;padding:2px 8px;border-radius:4px;font-family:monospace;margin-right:8px">${badge.l}</span><strong>${t.indicador}</strong><p style="margin:6px 0 0;color:#6b7280;font-size:12px">${t.analise}</p></div>`}).join("");
  return`<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;background:#f9fafb;font-family:'Segoe UI',system-ui,sans-serif"><div style="max-width:680px;margin:0 auto;padding:24px 16px"><div style="background:linear-gradient(135deg,#0a0c10,#1a1f2e);border-radius:12px;padding:28px 32px;margin-bottom:20px"><div style="font-size:11px;color:#00e5a0;font-family:monospace;letter-spacing:0.1em;margin-bottom:8px">✦ ANÁLISE EXECUTIVA AUTOMÁTICA</div><h1 style="color:#fff;font-size:22px;font-weight:800;margin:0 0 6px">Report Comercial Serviços</h1><div style="color:#6b7280;font-size:12px;font-family:monospace">${a.semana_referencia} · ${today}</div></div><div style="background:#fff;border-radius:10px;padding:20px 24px;margin-bottom:20px;border:1px solid #e5e7eb;border-left:4px solid #00e5a0"><div style="font-size:11px;font-weight:700;color:#00b37e;letter-spacing:0.08em;text-transform:uppercase;margin-bottom:10px">01 · Executive Summary</div><p style="margin:0;font-size:14px;line-height:1.7;color:#374151">${a.executive_summary}</p></div>${sec("02","Key Business Drivers","#3b82f6",drivers)}${sec("03","Structural Trends","#8b5cf6",trends)}${sec("04","Key Risks","#f97316",risks)}${sec("06","Recommended Actions","#10b981",actions)}<div style="margin-bottom:20px;border-radius:10px;overflow:hidden;border:1px solid #e5e7eb"><div style="background:#eff6ff;padding:12px 18px;border-bottom:1px solid #e5e7eb"><span style="font-weight:700;font-size:13px;color:#1d4ed8;text-transform:uppercase;letter-spacing:0.05em">07 · Questions for Leadership</span></div><div style="padding:16px 18px"><ul style="list-style:none;margin:0;padding:0">${questions}</ul></div></div><div style="text-align:center;padding:16px;color:#9ca3af;font-size:11px;font-family:monospace">Gerado automaticamente toda segunda-feira às 09:00 · <a href="https://dashboard-servicos.vercel.app" style="color:#00b37e;text-decoration:none">Ver Dashboard Completo →</a></div></div></body></html>`;
}

async function main(){
  try{
    console.log("🚀 Iniciando...");
    const r=await post("api.anthropic.com","/v1/messages",{"Content-Type":"application/json","x-api-key":ANTHROPIC_KEY,"anthropic-version":"2023-06-01"},{model:"claude-sonnet-4-20250514",max_tokens:2000,system:'Analista estrategico de marketplace de servicos. Responda SOMENTE JSON sem markdown sem backticks: {"semana_referencia":"string","executive_summary":"string","key_drivers":[{"indicador":"string","variacao":"string","drivers":["string"]}],"structural_trends":[{"indicador":"string","tipo":"crescimento consistente|queda consistente|volatilidade","analise":"string"}],"risks_anomalies":[{"risco":"string","driver":"string"}],"actions":[{"area":"string","acao":"string"}],"questions":["string"]}',messages:[{role:"user",content:DATA}]});
    const a=JSON.parse(r.content.map(b=>b.text||"").join("").replace(/```json|```/g,"").trim());
    console.log("✅ Analise gerada:",a.semana_referencia);
    const tr=nodemailer.createTransport({service:"gmail",auth:{user:GMAIL_USER,pass:GMAIL_PASS}});
    await tr.sendMail({from:`"Dashboard Servicos" <${GMAIL_USER}>`,to:RECIPIENTS.join(","),subject:`📊 Analise Executiva — ${a.semana_referencia}`,html:buildEmail(a)});
    console.log("✅ Email enviado para",RECIPIENTS.length,"destinatarios!");
  }catch(e){console.error("❌",e.message);process.exit(1)}
}
main();

